#!/bin/bash
set -e

LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
JEKRYPT_FOLDER="$LOCATION/.jekrypt"

source "$LOCATION/jekrypt.cfg"

mkdir -p "$JEKRYPT_FOLDER"

if [[ ! -f "$MASTERPASSWORD_LOCATION" ]]; then
  pwgen -s 64 1 > "$MASTERPASSWORD_LOCATION"
fi


if [[ -f "$MASTERPASSWORD_LOCATION" ]]; then
  MASTERPASSWORD="$(cat "$MASTERPASSWORD_LOCATION")"
else
  echo "Missing file or rights at $MASTERPASSWORD_LOCATION"
  echo "Stopping."
  return 1
fi

mkdir -p "$toencrypt"
mkdir -p "$encrypted"

declare -A kv

loadKVStore(){
    touch "$FILE"
    while IFS=' ' read -r key value
    do
        kv[$key]="$value"
    done < "$FILE"
}

get(){
    loadKVStore
    echo "${kv[$1]}"
}

put(){
    loadKVStore
    kv["$1"]="$2"
    rm "$FILE"
    for i in "${!kv[@]}"
    do
        echo "$i ${kv[$i]}" >> "$FILE"
    done
}

exportAsYML(){
    loadKVStore
    rm "$EXPORT"
    for i in "${!kv[@]}"
    do
        echo "- link: $i" >> "$EXPORT"
        echo "  password: ${kv[$i]}" >> "$EXPORT"
    done
}

# $1 file to encrypt
# $2 destination
# $3 password
encryptFile(){
    TEXT=$(cat "$1")
    echo "$TEXT"
    DEST="$2"/"$(decryptedFileToKey "$1")"
    FRONTMATTER=$(frontMatter "$TEXT")
    ENCRYPTED=$(partToEncrypt "$TEXT" | kramdown | gpg --quiet --passphrase="$3" --batch --armor -c - | base64 | tr -d '\n')
    ORIGINAL_ENCRYPTED=$(partToEncrypt "$TEXT" | gpg --quiet --passphrase="$3" --batch --armor -c - | base64 | tr -d '\n')
    FILENAME="$(basename "$1" | gpg --quiet --passphrase="$3" --batch --armor -c - | base64 | tr -d '\n')"
    {
        echo "---";
        echo "$FRONTMATTER";
        echo "original_content: $ORIGINAL_ENCRYPTED";
        echo "filename: $FILENAME"
        echo "---";
        echo "";
        echo "$ENCRYPTED";
    } > "$DEST"
}

# $1 file to decrypt
# $2 destination
# $3 password
decryptFile(){
    TEXT=$(cat "$1" | grep -v "private: true")
    DEST="$2/$(basename "$1")"
    FRONTMATTER=$(frontMatter "$TEXT")
    ENCRYPTED=$(originalContent "$TEXT" | base64 -d | gpg --batch --passphrase="$3" -d -)
    {
        echo "---";
        echo "$FRONTMATTER";
        echo "---";
        echo "";
        echo "$ENCRYPTED";
    } > "$DEST"
}

frontMatterEnd(){
    echo "$1" | grep -n "\-\-\-" | head -n 2 | tail -n 1 | sed -E 's/(.*):.*/\1/g'
}

frontMatter(){
    END=$(frontMatterEnd "$1")
    echo  "$1" | head -n "$END" | grep -v "original_content: *" | grep -v "\-\-\-"
}

partToEncrypt(){
    echo  "$1" | tr '\n' '~' | sed -E 's/\-\-\-.*\-\-\-~+(.*)/\1/g' | tr '~' '\n'
}

originalContent(){
    echo  "$1" | grep "original_content:" | sed -E 's/original_content: (.*)/\1/g'
}

encryptText(){
    echo "ENCRYPTED TEXT"
}

getPassword(){
    VALUE=$(get "$1")
    if [[ -z "$VALUE" ]]; then
        VALUE=$(pwgen -s 64 1)
        ENCRYPTEDPASS=$(echo "$VALUE" | gpg --quiet --passphrase="$MASTERPASSWORD" --batch --armor -c -  | base64 | tr -d '\n')
        put "$1" "$ENCRYPTEDPASS"
        echo "$VALUE"
    else
        DECRYPTED="$(echo "$VALUE" | base64 -d  | gpg --batch --passphrase="$MASTERPASSWORD" -d -)"
        echo "$DECRYPTED"
    fi


}

decryptedFileToKey(){
  b="$(basename "$1")"
  datePart="${b:0:10}"
  textPart="${b:11}"
  shaText="$(echo "$textPart" | sha256sum | tr -d ' -')"
  echo "$datePart-${shaText:0:10}"
}

encryptAll(){
    if [[ -n "$(ls -A "$1")" ]]; then
        for f in "$1"/*; do
            echo "$f"
            KEY="$(decryptedFileToKey "$f")"
            PASS="$(getPassword "$KEY")"
            echo "LINK: $KEY $f $PASS"
            encryptFile "$f" "$2" "$PASS"

            # PASS="$(getPassword "$(basename "$f")")"
            # encryptFile "$f" "$2" "$PASS"
            # echo "LINK: $f $PASS"
        done
        #exportAsYML
    fi
}

decryptAll(){
    if [[ -n "$(ls -A "$1")" ]]; then
        for f in "$1"/*; do
            EXISTS=$(get "$(basename "$f")")
            if [[ -n "$EXISTS" ]]; then
                echo "Decrypting $f"
                VALUE=$(getPassword "$(basename "$f")")
                decryptFile "$f" "$2" "$VALUE"
                echo "Decrypted $f"
            fi

        done
        exportAsYML
    fi
}

if [[ ! $# -eq 0 ]] ; then
    case "$1" in
        "--encrypt-all") encryptAll "$toencrypt" "$encrypted" ;;
        "--decrypt-all") decryptAll "$encrypted" "$toencrypt" ;;
    esac
fi
